"""add isComplete column into todos

Revision ID: dc6f5f89e55a
Revises: 9ce65be720bd
Create Date: 2025-10-06 22:43:20.147391

"""
from typing import Sequence
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc6f5f89e55a'
down_revision: str | Sequence[str] | None = '9ce65be720bd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'todos',
        sa.Column('isComplete', sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        "todos",
        'isComplete'
    )
    # ### end Alembic commands ###
