"""todos table add user_id column

Revision ID: g50951ef0588b
Revises: 975ec80664df
Create Date: 2025-11-05 01:23:19.786237

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'g50951ef0588b'
down_revision: str | Sequence[str] | None = '975ec80664df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """ todos 新增 user_id 欄位及建立外鍵關聯   """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        "todos_fk_1", # 外鍵約束名稱（如果不給，Alembic 會自動生成）
        'todos', # 來源資料表
        'users', # 被參照的資料表
        ['user_id'], # 來源表的欄位
        ['id'], # 被參照表的欄位
        onupdate="RESTRICT",
        ondelete="RESTRICT"
        )
    op.execute("UPDATE `todos` SET `user_id` = 1") # 為 user_id 給值


def downgrade() -> None:
    """ 刪除 todos 外鍵關聯以及 user_id 欄位  """
    op.drop_constraint("todos_fk_1", 'todos', type_='foreignkey')
    op.drop_column('todos', 'user_id')
